- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: dev-game-app
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: ndcmgmt-cluster
          organization: Default
